/// Parah (Juz) Model
/// Represents a single Parah/Juz from the Quran
class ParahModel {
  final int number;
  final String arabicName;
  final String englishName;
  final int startSurah;
  final int startAyah;
  final int endSurah;
  final int endAyah;

  const ParahModel({
    required this.number,
    required this.arabicName,
    required this.englishName,
    required this.startSurah,
    required this.startAyah,
    required this.endSurah,
    required this.endAyah,
  });

  /// Static list of all 30 Parahs with their Arabic names
  /// Since AlQuran Cloud API doesn't provide a direct Parah list endpoint,
  /// we use predefined data with correct Arabic names
  static List<ParahModel> getAllParahs() {
    return [
      const ParahModel(
        number: 1,
        arabicName: 'الٓمٓ',
        englishName: 'Alif Lam Meem',
        startSurah: 1,
        startAyah: 1,
        endSurah: 2,
        endAyah: 141,
      ),
      const ParahModel(
        number: 2,
        arabicName: 'سَيَقُولُ',
        englishName: 'Sayaqool',
        startSurah: 2,
        startAyah: 142,
        endSurah: 2,
        endAyah: 252,
      ),
      const ParahModel(
        number: 3,
        arabicName: 'تِلْكَ ٱلرُّسُلُ',
        englishName: 'Tilkal Rusul',
        startSurah: 2,
        startAyah: 253,
        endSurah: 3,
        endAyah: 92,
      ),
      const ParahModel(
        number: 4,
        arabicName: 'لَن تَنَالُوا۟',
        englishName: 'Lantanalu',
        startSurah: 3,
        startAyah: 93,
        endSurah: 4,
        endAyah: 23,
      ),
      const ParahModel(
        number: 5,
        arabicName: 'وَٱلْمُحْصَنَـٰتُ',
        englishName: 'Wal Mohsanat',
        startSurah: 4,
        startAyah: 24,
        endSurah: 4,
        endAyah: 147,
      ),
      const ParahModel(
        number: 6,
        arabicName: 'يَـٰٓأَيُّهَا ٱلَّذِينَ ءَامَنُوا۟',
        englishName: 'Ya Ayyuhal',
        startSurah: 4,
        startAyah: 148,
        endSurah: 5,
        endAyah: 81,
      ),
      const ParahModel(
        number: 7,
        arabicName: 'وَإِذَا سَمِعُوا۟',
        englishName: "Wa Iza Sami'u",
        startSurah: 5,
        startAyah: 82,
        endSurah: 6,
        endAyah: 110,
      ),
      const ParahModel(
        number: 8,
        arabicName: 'وَلَوْ أَنَّنَا',
        englishName: 'Wa Lau Annana',
        startSurah: 6,
        startAyah: 111,
        endSurah: 7,
        endAyah: 87,
      ),
      const ParahModel(
        number: 9,
        arabicName: 'قَالَ ٱلْمَلَأُ',
        englishName: "Qalal Mala'u",
        startSurah: 7,
        startAyah: 88,
        endSurah: 8,
        endAyah: 40,
      ),
      const ParahModel(
        number: 10,
        arabicName: 'وَٱعْلَمُوٓا۟',
        englishName: "Wa'lamu",
        startSurah: 8,
        startAyah: 41,
        endSurah: 9,
        endAyah: 92,
      ),
      const ParahModel(
        number: 11,
        arabicName: 'يَعْتَذِرُونَ',
        englishName: "Ya'tazirun",
        startSurah: 9,
        startAyah: 93,
        endSurah: 11,
        endAyah: 5,
      ),
      const ParahModel(
        number: 12,
        arabicName: 'وَمَا مِن دَآبَّةٍۢ',
        englishName: 'Wa Ma Min Dabbah',
        startSurah: 11,
        startAyah: 6,
        endSurah: 12,
        endAyah: 52,
      ),
      const ParahModel(
        number: 13,
        arabicName: 'وَمَآ أُبَرِّئُ',
        englishName: "Wa Ma Ubari'u",
        startSurah: 12,
        startAyah: 53,
        endSurah: 14,
        endAyah: 52,
      ),
      const ParahModel(
        number: 14,
        arabicName: 'رُبَمَا',
        englishName: 'Rubama',
        startSurah: 15,
        startAyah: 1,
        endSurah: 16,
        endAyah: 128,
      ),
      const ParahModel(
        number: 15,
        arabicName: 'سُبْحَـٰنَ ٱلَّذِىٓ',
        englishName: 'Subhanallazi',
        startSurah: 17,
        startAyah: 1,
        endSurah: 18,
        endAyah: 74,
      ),
      const ParahModel(
        number: 16,
        arabicName: 'قَالَ أَلَمْ',
        englishName: 'Qala Alam',
        startSurah: 18,
        startAyah: 75,
        endSurah: 20,
        endAyah: 135,
      ),
      const ParahModel(
        number: 17,
        arabicName: 'ٱقْتَرَبَ لِلنَّاسِ',
        englishName: 'Iqtaraba',
        startSurah: 21,
        startAyah: 1,
        endSurah: 22,
        endAyah: 78,
      ),
      const ParahModel(
        number: 18,
        arabicName: 'قَدْ أَفْلَحَ',
        englishName: 'Qad Aflaha',
        startSurah: 23,
        startAyah: 1,
        endSurah: 25,
        endAyah: 20,
      ),
      const ParahModel(
        number: 19,
        arabicName: 'وَقَالَ ٱلَّذِينَ',
        englishName: 'Wa Qalallazina',
        startSurah: 25,
        startAyah: 21,
        endSurah: 27,
        endAyah: 55,
      ),
      const ParahModel(
        number: 20,
        arabicName: 'أَمَّنْ خَلَقَ',
        englishName: 'Amman Khalaqa',
        startSurah: 27,
        startAyah: 56,
        endSurah: 29,
        endAyah: 45,
      ),
      const ParahModel(
        number: 21,
        arabicName: 'أُتْلُ مَآ أُوحِىَ',
        englishName: 'Utlu Ma Uhiya',
        startSurah: 29,
        startAyah: 46,
        endSurah: 33,
        endAyah: 30,
      ),
      const ParahModel(
        number: 22,
        arabicName: 'وَمَن يَقْنُتْ',
        englishName: 'Wa Man Yaqnut',
        startSurah: 33,
        startAyah: 31,
        endSurah: 36,
        endAyah: 27,
      ),
      const ParahModel(
        number: 23,
        arabicName: 'وَمَا لِىَ',
        englishName: 'Wa Mali',
        startSurah: 36,
        startAyah: 28,
        endSurah: 39,
        endAyah: 31,
      ),
      const ParahModel(
        number: 24,
        arabicName: 'فَمَنْ أَظْلَمُ',
        englishName: 'Fa Man Azlamu',
        startSurah: 39,
        startAyah: 32,
        endSurah: 41,
        endAyah: 46,
      ),
      const ParahModel(
        number: 25,
        arabicName: 'إِلَيْهِ يُرَدُّ',
        englishName: 'Ilaihi Yuraddu',
        startSurah: 41,
        startAyah: 47,
        endSurah: 45,
        endAyah: 37,
      ),
      const ParahModel(
        number: 26,
        arabicName: 'حمٓ',
        englishName: 'Ha Meem',
        startSurah: 46,
        startAyah: 1,
        endSurah: 51,
        endAyah: 30,
      ),
      const ParahModel(
        number: 27,
        arabicName: 'قَالَ فَمَا خَطْبُكُمْ',
        englishName: 'Qala Fama Khatbukum',
        startSurah: 51,
        startAyah: 31,
        endSurah: 57,
        endAyah: 29,
      ),
      const ParahModel(
        number: 28,
        arabicName: 'قَدْ سَمِعَ ٱللَّهُ',
        englishName: 'Qad Sami Allah',
        startSurah: 58,
        startAyah: 1,
        endSurah: 66,
        endAyah: 12,
      ),
      const ParahModel(
        number: 29,
        arabicName: 'تَبَـٰرَكَ ٱلَّذِى',
        englishName: 'Tabarakallazi',
        startSurah: 67,
        startAyah: 1,
        endSurah: 77,
        endAyah: 50,
      ),
      const ParahModel(
        number: 30,
        arabicName: 'عَمَّ يَتَسَآءَلُونَ',
        englishName: 'Amma Yatasa alun',
        startSurah: 78,
        startAyah: 1,
        endSurah: 114,
        endAyah: 6,
      ),
    ];
  }
}
